[env:native]
platform = native
test_framework = unity
build_type = debug
build_flags = 
    -std=c++11
    -UUNITY_INCLUDE_CONFIG_H
    -I .pio/libdeps/native/Unity/src
    -I lib
    -I test/mocks
lib_deps = 
    throwtheswitch/Unity@^2.5.2