name: Notify Discord on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "content": "A new PR has been opened by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}\nPlease review it!"
            }' \
            "$DISCORD_WEBHOOK"
